version: "3.8"

services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: product-catalog-management
      MYSQL_USER: user
      MYSQL_PASSWORD: 12345
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  mysql_test:
    image: mysql:latest
    container_name: mysql-test-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: product-catalog-management-test
      MYSQL_USER: user
      MYSQL_PASSWORD: 12345
    ports:
      - "3307:3306" # Mapeando para uma porta diferente para evitar conflitos
    volumes:
      - mysql-test-data:/var/lib/mysql

volumes:
  mysql-data:
    driver: local
  mysql-test-data:
    driver: local
